# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Pods for Mobile-Application

pod 'SVProgressHUD'
pod 'SwiftyJSON'
pod 'Alamofire'
pod 'Firebase/Auth'
pod 'GoogleSignIn', '~> 5.0'
pod 'Firebase/Firestore'
pod 'Firebase/Analytics'

target 'Mobile-Application' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!



  target 'Mobile-ApplicationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Mobile-ApplicationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
